Dream\NavInvoiceData\ProductFeeDataType:
    properties:
        productFeeCode:
            expose: true
            access_type: public_method
            serialized_name: productFeeCode
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getProductFeeCode
                setter: setProductFeeCode
            type: Dream\NavInvoiceData\ProductCodeType
        productFeeQuantity:
            expose: true
            access_type: public_method
            serialized_name: productFeeQuantity
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getProductFeeQuantity
                setter: setProductFeeQuantity
            type: float
        productFeeMeasuringUnit:
            expose: true
            access_type: public_method
            serialized_name: productFeeMeasuringUnit
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getProductFeeMeasuringUnit
                setter: setProductFeeMeasuringUnit
            type: string
        productFeeRate:
            expose: true
            access_type: public_method
            serialized_name: productFeeRate
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getProductFeeRate
                setter: setProductFeeRate
            type: float
        productFeeAmount:
            expose: true
            access_type: public_method
            serialized_name: productFeeAmount
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getProductFeeAmount
                setter: setProductFeeAmount
            type: float
