Dream\NavInvoiceData\ProductCodeType:
    properties:
        productCodeCategory:
            expose: true
            access_type: public_method
            serialized_name: productCodeCategory
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getProductCodeCategory
                setter: setProductCodeCategory
            type: string
        productCodeValue:
            expose: true
            access_type: public_method
            serialized_name: productCodeValue
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getProductCodeValue
                setter: setProductCodeValue
            type: string
        productCodeOwnValue:
            expose: true
            access_type: public_method
            serialized_name: productCodeOwnValue
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getProductCodeOwnValue
                setter: setProductCodeOwnValue
            type: string
