Dream\NavInvoiceData\ProductFeeTakeoverDataType:
    properties:
        takeoverReason:
            expose: true
            access_type: public_method
            serialized_name: takeoverReason
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getTakeoverReason
                setter: setTakeoverReason
            type: string
        takeoverAmount:
            expose: true
            access_type: public_method
            serialized_name: takeoverAmount
            xml_element:
                namespace: 'http://schemas.nav.gov.hu/OSA/1.0/data'
            accessor:
                getter: getTakeoverAmount
                setter: setTakeoverAmount
            type: float
